theme: minima
title: The Shra Blog
author: Shbhareya
email: nottellingya@domain.com
description: > # this means to ignore newlines until "baseurl:"
  A random blog started by somebody who doesn't know what she's doing :D 

# social links
twitter_username: but wae
github_username: Shbhareya

show_excerpts: false # set to false to remove excerpts on the homepage
